library: user_detail

collections: 
- name: user_details_collection
  format: delimitedFile
  filePatterns:
  - /home/deuser/workspaces/dejpsoldefloc/JP_10-JAN_25/common/sample_data/people-120-records.csv
  schema: user_details_schema
  enableFileSplits: true
schemas: 
- name: user_details_schema
  columns:
  - name: Index
    typeID: Common:Integer
    timeZone: '-'
  - name: User_Id
    typeID: Common:String
    timeZone: '-'
    displayName: ""
    desc: ""
  - name: First_Name
    typeID: Common:String
    timeZone: '-'
    displayName: ""
    desc: ""
  - name: Last_Name
    typeID: Common:String
    timeZone: '-'
    displayName: ""
    desc: ""
  - name: Sex
    typeID: Common:String
    timeZone: '-'
  - name: Email
    typeID: Common:String
    timeZone: '-'
  - name: Phone
    typeID: Common:String
    timeZone: '-'
  - name: Date_of_birth
    typeID: Common:String
    timeZone: '-'
    displayName: ""
    desc: ""
  - name: Job_Title
    typeID: Common:String
    timeZone: '-'
    displayName: ""
    desc: ""
  - name: Age
    typeID: Common:Integer
    timeZone: '-'
  - name: Income
    typeID: Common:Integer
    timeZone: '-'
  - name: Tax_Submitted
    typeID: Common:Integer
    timeZone: '-'
    displayName: ""
    desc: ""

views: 
- name: user_details_view
  engine: SPARK
  transformations:
  - as: viewInput
    operation: viewInput
    inputs:
      inview: user_details_schema
  - as: map
    operation: map
    source: inview
    mappings:
    - sourcePattern: ".*"
      transformations:
      - operation: "replaceAll"
        substring: "-"
        with: " "
      - operation: "removeAll"
        substring: " "
  - as: viewOutput
    operation: viewOutput
    outputs:
    - map
  outputDefinition:
    type: virtual

  